@startuml
scale 2
title "UML Class Diagram"
class CheckPalindrome {
    -_morse_text : str

    +__init__(morse_text: str) : None
    +morse_text : str
	+morse_text() : str
    +morse_text(newMorse_Text: str) : None
	+isPalindrome() : int
}
@enduml