@startuml
scale 2
title "UML Class Diagram"
class Data {
    +_location() : str

    +__init__(location: str) : None
    +location: str
    +getURL(search_input: str) : str
    +city(data: typing.Any) : str
    +general(data: typing.Any) : str
    +wind(data: typing.Any) : str
    +time(data: typing.Any) : str
}
@enduml